version: "3.8"

services:
  tor-proxy:
    build:
      context: ./
      dockerfile: tor-proxy
      labels:
        - "tor-proxy"
    container_name: "tor-proxy-relay"
    networks:
      - outbound-proxy
    volumes:
      - ${PWD}/tor/resolv.conf:/etc/resolv.conf

  splash:
    image: scrapinghub/splash
    ports:
      - "127.0.0.1:8050:8050"
    container_name: "splash_renderer"
    networks:
      - outbound-proxy
    volumes:
       - ./splash:/etc/splash/proxy-profiles:ro

#volumes:
#  splash-proxy-profiles:
#  - ./splash

networks:
  outbound-proxy:
