version: "3.8"

services:
  tor-proxy:
    build:
      context: ./
      dockerfile: tor-proxy
      labels:
        - "tor-proxy"
    container_name: "tor-proxy-relay"
    networks:
      - outbound-proxy

  splash:
    image: scrapinghub/splash
    ports:
      - "127.0.0.1:8050:8050"
    container_name: "splash-renderer"
    networks:
      - outbound-proxy
    volumes:
       - ./splash:/etc/splash/proxy-profiles:ro


networks:
  outbound-proxy:
